# netlify.toml
# Configuração completa para deploy no Netlify

[build]
  # Diretório onde estão os arquivos buildados
  publish = "dist"
  
  # Comando para fazer build da aplicação
  command = "npm run build"
  
  # Ignorar builds se apenas arquivos específicos mudaram
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- README.md docs/"

[build.environment]
  # Versão do Node.js a usar
  NODE_VERSION = "18"
  
  # Configurações do npm
  NPM_FLAGS = "--production=false"
  
  # Configurações do Vite para produção
  NODE_ENV = "production"

# Configuração para produção
[context.production]
  command = "npm run build"
  
[context.production.environment]
  # Variáveis de ambiente para produção
  # NOTA: Adicione as variáveis sensíveis através do painel do Netlify UI
  NODE_ENV = "production"

# Configuração para preview de branches
[context.deploy-preview]
  command = "npm run build"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Configuração para branches específicos (ex: desenvolvimento)
[context.branch-deploy]
  command = "npm run build"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para arquivos JavaScript e CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de otimização
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true